global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nextjs-app'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['nextjs-app:3000']

  - job_name: 'mongodb'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['mongodb-exporter:9216']    
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:9121']